### ISSUE TITLE
WM ext - key security, use & storage (exploratory ticket)

### ISSUE THREAD

**Issue by ionutanin** [interledger/web-monetization-extension#27]
Store secret keys into extension storage
Generate key/pair for extension

**Comment by dianafulga** [comment]
Web extension storage
 
Strengths:
-       Isolation: Data stored using chrome.storage.local is isolated to the extension's origin. Other extensions or web pages cannot access this data directly.
-       Encryption: The data stored using Chrome's storage API is encrypted at rest by default. This encryption protects the data from casual inspection outside of the extension's context.
-       Chrome Extension Sandbox: Extensions run in a sandboxed environment, which provides an additional layer of security by restricting their access to browser functionalities and resources.
 
Vulnerabilities
-       Encryption Strength: While Chrome Storage API encrypts data at rest, it might not provide the highest level of encryption compared to custom encryption techniques or external encryption libraries. Thus, it may be vulnerable to sophisticated attacks.
-       Extension Vulnerabilities: Security vulnerabilities within the extension itself, such as XSS (Cross-Site Scripting) vulnerabilities or compromised extension permissions, could potentially expose data stored using the Chrome Storage API.
-       Limited to Extension Context: Although the data is isolated within the extension's context, it's crucial to be mindful of the permissions granted to the extension and how they might affect data security.
 
 
 
I.               Storage is protected against remote attacks due to isolation & sandbox env. 
 
II.             If the attacker has access to user’s computer, we need to encrypt the storage.
 
 
1.    Backend authentication 
1.1.    Create account.
1.2.    When adding the key:
-       Request backend to generate a password based on token.
-       Encrypt key with password on frontend and store it in storage.
1.3.     When using the key:
-       Request password from backend based on token (cached)
-       Decrypt key (and store it in memory with timer to avoid decryption all the time if needed)
 
2.    Local auth
2.1.    When adding the key
-       Request password
-       Encrypt key with password and store it in storage.
2.2.    When using the key:
-       Request password
-       Decrypt key and store it in memory with timer.

**Comment by raducristianpopa** [comment]
Temporary decision:
- for development: local signature server to generate HTTP Signatures
- for production use: Cloud Function to to generate HTTP Signatures
